server.port=9091
spring.data.mongodb.uri=mongodb+srv://ash:9480@cluster0.5hu7rml.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=librarydb
spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN